services:
  server:
    develop:
      watch:
        - action: rebuild
          path: ./src
        - action: rebuild
          path: ./Cargo.toml
        - action: rebuild
          path: ./Cargo.lock
        - action: restart
          path: ./.env
