FROM quay.io/keycloak/keycloak:26.7.0@sha256:0f198be292568439d700cdbfb893e69a6009bb43a94a06a945b1d3d506c76b13

COPY --chown=keycloak:keycloak config/keycloak/ofk-realm.json /opt/keycloak/data/import/ofk-realm.json
