FROM quay.io/keycloak/keycloak:26.7.1@sha256:f1f1f01e472c8a78df40d8f2a49a925274eda4d3d80d5f6edbb5c880ee3c01c6

COPY --chown=keycloak:keycloak config/keycloak/ofk-realm.json /opt/keycloak/data/import/ofk-realm.json
